# Generated by Django 5.1.15 on 2026-08-14 09:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_organiz_c1c99d_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_resourc_2a3aef_idx',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='resource_type',
            new_name='target_model',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='changes',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='resource_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='changes_json',
            field=models.JSONField(default=dict, help_text='Diff showing changed fields'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('WORKFLOW_TRANSITION', 'Workflow Transition'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', '-timestamp'], name='audit_audit_organiz_155e59_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_model', 'target_id'], name='audit_audit_target__573821_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', '-timestamp'], name='audit_audit_actor_i_dcd783_idx'),
        ),
    ]
